name: build

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: deploy
  jobs:
  - job: deploy
    displayName: Deploy containers to dockerhub
    variables:
      - group: deployment-information
    steps:
    - task: Docker@2
      displayName: Login to docker hub
      inputs:
        command: login
        containerRegistry: dockerhub
    - script: |
        set -xv  # Echo commands before they are run
        export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
        docker build --build-arg version=$TAG -t cccs/assemblyline-service-deobfuscripter:$TAG -t cccs/assemblyline-service-deobfuscripter:latest .
        docker push cccs/assemblyline-service-deobfuscripter
      displayName: Deploy to Docker Hub
