extends:
  parameters:
    is_public: 'true'
    labels:
      classification: UNCLASSIFIED
    samples_repo: unittest-samples
  template: stages/deploy-service.yaml@PipelineTemplates
name: build
pool:
  vmImage: ubuntu-latest
pr: none
resources:
  repositories:
  - endpoint: github-repo-sa
    name: CybercentreCanada/assemblyline-pipeline-templates
    ref: refs/heads/main
    repository: PipelineTemplates
    trigger: none
    type: github
  - endpoint: github-repo-sa
    name: $(unittest_samples_repository)
    ref: main
    repository: unittest-samples
    trigger: none
    type: github
trigger:
  tags:
    include:
    - v*
variables:
- group: unittest-samples
